name: Deploy to Firebase Hosting on PR
'on': pull_request

env:
  VITE_FIREBASE_APIKEY: ${{ secrets.VITE_FIREBASE_APIKEY }}
  VITE_FIREBASE_AUTHDOMAIN: ${{ secrets.VITE_FIREBASE_AUTHDOMAIN }}
  VITE_FIREBASE_PROJECTID: ${{ secrets.VITE_FIREBASE_PROJECTID }}
  VITE_FIREBASE_STORAGEBUCKET: ${{ secrets.VITE_FIREBASE_STORAGEBUCKET }}
  VITE_FIREBASE_MESSAGINGSENDERID: ${{ secrets.VITE_APP_FIREBASE_MESSAGINGSENDERID }}
  VITE_FIREBASE_APIID: ${{ secrets.VITE_FIREBASE_APIID }}

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build app
        run: yarn build

      - name: Run tests
        run: test:unit:run

  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build app
        run: yarn build

      - name: Firebase preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GITHUB_DISCOVERY_D894A }}'
          projectId: github-discovery-d894a
